### ISSUE TITLE
Segfault when opening the "Switch users" prompt in Google Chrome

### ISSUE THREAD

**Issue by JeffHoogland** [JeffHoogland/moksha#13]
When you select the "switch user" option in Chrome the desktop segfaults as the window that pops up opens.

It segfaults again instantly when you restart / hit F1. If you drop to a TTY and kill Chrome you can then restart the desktop without issue.

Something in how Moksha is handling the Chrome sub window that is created must be causing the segfault.

http://i.imgur.com/zi77hBg.png

**Comment by drammelt** [comment]
Confirmed. Is a result of a backport, tracking down now.

**Comment by drammelt** [comment]
Fixed with revert of 57181cec84b0d70ade94c624934046f5f71d50c4
Probably a NULL value passed in by the Chrome window.

**Comment by JeffHoogland** [comment]
What was commit 57181ce fixing / back porting? Is it something we need? I wonder if this same issue happens in newer E versions.

**Comment by drammelt** [comment]
This will not affect newer versions as they do not use e_border.c anymore. I would say the fix was probably broken in the first place and just abandoned when they switched to the e_client.c API.
It should have fixed window detection for clients with miss matched WM_CLASS names, like "firefox" -> "Firefox", the WM_CLASS setting in desktop files can solve this anyway so its not a huge deal.

**Comment by drammelt** [comment]
I stand corrected. This was ported into the new e_client.c, and looks very different in terms of nesting. I will test the new commit and see how it works.

**Comment by drammelt** [comment]
Actually fixed with c48d5bfb3bf8ebacc149e1d83bdfc9e5f589c18b.
The nesting was incorrect and there was a potential buffer underrun when copying the buffer.

**Comment by JeffHoogland** [comment]
Awesome. Will test this later this evening.

**Comment by JeffHoogland** [comment]
Confirmed this fix works.
